- hosts: localhost
  tasks:
  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: "Install required software"
    become: true
    package:
      name:
        - git
        - curl
        - rsync
        - build-essential
        - tmux
        - python3-pip
        - python3-venv
        - fzf
        - ripgrep
        - xclip
        - jq
        - zsh
        - unzip
        - bat
      state: present

  - name: user.name for git config
    become_user: "{{ username }}"
    community.general.git_config:
      name: user.name
      scope: global
      value: "{{ username }}"

  - name: user.email for git config
    become_user: "{{ username }}"
    community.general.git_config:
      name: user.email
      scope: global
      value: "{{ email }}"

  - name: Install desktop applications
    become: true
    package:
      name:
        - firefox
      state: present

  - name: Ensure zsh is the default shell
    user:
      name: "{{ ansible_user_id }}"
      shell: "/usr/bin/zsh"
    become: true

  - name: Download Oh My Zsh installation script
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install_ohmyzsh.sh

  - name: Run Oh My Zsh installation script
    command: sh /tmp/install_ohmyzsh.sh --unattended
    register: ohmyzsh_result
    failed_when: "'FAILED' in ohmyzsh_result.stderr"

  - name: Install zsh-syntax-highlighting plugin # latest[git]
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: Install zsh-autosuggestions plugin # latest[git]
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

  - name: Install zsh-completions plugin # latest[git]
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-completions

  - name: Copy dev env dotfiles
    ansible.builtin.copy:
      src: ../env/
      dest: "{{ home }}"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0755'

  - name: Copy local scripts
    ansible.builtin.copy:
      src: ../scripts/
      dest: "{{ local_scripts }}"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0755'
